### ISSUE TITLE
网页错字反馈

### ISSUE THREAD

**Issue by Hakuin123** [theme-keep/hexo-theme-keep-docs-v3#1]
https://keep-docs.xpoet.cn/tutorial/configuration-guide/menu.html#跳转内部页面

>打开 Hexo 项目下 /source/about/index.md 文件，填写 **Adout** 页面的内容。 支持 Markdown 和 HTML 格式； 

这里的`Adout`应更正为`About`

**Comment by XPoet** [comment]
感谢反馈，已更改
